version: '3.1'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - go-api-net
  
  go-crud:
    image: juniorpaiva/go-api:1.1
    restart: always
    container_name: go-crud
    networks:
      - go-api-net
    depends_on:
      - mongodb
    ports:
      - "9080:9080"
    environment:
      MONGO_DB_HOST: mongodb

networks:
  go-api-net:

volumes:
  mongodb_data:

