version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - go-api-net
    ports:
      - "27017:27017"
  
  go-crud:
    image: juniorpaiva/go-api:1.0
    container_name: go-crud
    networks:
      - go-api-net
    depends_on:
      - mongodb
    ports:
      - "9080:9080"
    enviroment:
      - MONGO_DB_HOST="mongodb"

networks:
  go-api-net:

volumes:
  mongodb_data:


